language: python
sudo: required
services:
  - docker
before_install:
  - docker pull pierky/bird:1.6.3 
install:
  - pip install -r requirements.txt
env:
  - TRAVIS_CI=1
script:
  - nosetests -vs tests/
