language: python
sudo: required
env:
  - TOXENV=py34-syntax
  - TOXENV=py27-flake8
  - TOXENV=py34-flake8
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py27-coverage
services:
  - docker
before_install:
  - docker pull pierky/bird:1.6.3 
install:
  - pip install tox
  - pip install coveralls
script:
 - tox
after_success:
 - coveralls
