language: python
sudo: required
services:
  - docker
before_install:
  - docker pull pierky/bird:1.6.3 
install:
  - pip install -r requirements.txt
script:
 - nosetests -vs tests/static/
 - nosetests -vs tests/live_tests/
